import AppKit
import CryptoKit
import ImageIO
import UniformTypeIdentifiers

extension Notification.Name {
    static let neClipCaptureDidSkip = Notification.Name("org.affpapa.neclip.captureDidSkip")
    static let neClipCaptureDidFail = Notification.Name("org.affpapa.neclip.captureDidFail")
}

enum ClipboardCapturePolicy {
    static let maxTextBytes = 2 * 1024 * 1024
    static let maxRTFBytes = 5 * 1024 * 1024
    static let maxEncodedImageBytes = 10 * 1024 * 1024
    static let maxImagePixels = 32_000_000
    static let maxFileCount = 256
    static let excludedActivationWindow: TimeInterval = 0.8

    static func effectiveTextPayloadLimit(userLimit: Int) -> Int {
        min(maxTextBytes, max(1, userLimit))
    }

    static func acceptsTextPayload(textBytes: Int, rtfBytes: Int, userLimit: Int) -> Bool {
        guard textBytes > 0, rtfBytes >= 0 else { return false }
        return textBytes + rtfBytes <= effectiveTextPayloadLimit(userLimit: userLimit)
    }

    static func shouldRejectSource(
        bundleID: String?,
        excludedTransitionActive: Bool,
        excludedApps: Set<String>
    ) -> Bool {
        guard let bundleID else { return true }
        return excludedTransitionActive || excludedApps.contains(bundleID)
    }

    static func acceptsImage(byteCount: Int, width: Int, height: Int) -> Bool {
        guard byteCount > 0, byteCount <= maxEncodedImageBytes,
              width > 0, height > 0 else { return false }
        return width <= maxImagePixels / height
    }
}

enum ClipboardCaptureSkipReason: String, Equatable {
    case ownWrite
    case ignoredOnce
    case paused
    case protectedType
    case excludedOrUnknownSource
    case empty
    case tooLarge
    case invalidImage
    case disabledContentType
    case sensitiveContent
    case pasteboardAccessDenied
}

/// Remembers exact pasteboard generations observed while leaving an excluded
/// app. A delayed timer tick must reject that copy even after the short
/// transition grace period has elapsed.
struct ClipboardExcludedChangeGuard {
    private(set) var pending: [Int] = []
    let capacity: Int

    init(capacity: Int = 8) {
        self.capacity = max(1, capacity)
    }

    mutating func record(changeCount: Int) {
        guard !pending.contains(changeCount) else { return }
        pending.append(changeCount)
        if pending.count > capacity {
            pending.removeFirst(pending.count - capacity)
        }
    }

    mutating func consumeIfExcluded(changeCount: Int) -> Bool {
        guard let index = pending.firstIndex(of: changeCount) else { return false }
        pending.remove(at: index)
        return true
    }
}

/// Mutable observer/timer state is main-thread confined; background work is
/// immutable snapshots on one serial queue.
final class ClipboardMonitor: @unchecked Sendable {
    private struct Snapshot: @unchecked Sendable {
        let changeCount: Int
        let appBundleID: String
        let createdAt: Date
        let fileURLs: [URL]
        let imageData: Data?
        let imageDataIsPNG: Bool
        let text: String?
        let rtf: Data?
    }

    private static let concealedTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    ]

    private let processingQueue = DispatchQueue(
        label: "org.affpapa.neclip.clipboard-processing",
        qos: .utility
    )
    private var timer: Timer?
    private var activationObserver: NSObjectProtocol?
    private var lastChangeCount = NSPasteboard.general.changeCount
    private var lastActivatedBundleID = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
    private var excludedTransitionUntil: Date?
    private var excludedChangeGuard = ClipboardExcludedChangeGuard()

    func start() {
        precondition(Thread.isMainThread)
        guard timer == nil else { return }

        activationObserver = NSWorkspace.shared.notificationCenter.addObserver(
            forName: NSWorkspace.didActivateApplicationNotification,
            object: nil,
            queue: .main
        ) { [weak self] notification in
            self?.applicationDidActivate(notification)
        }

        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            self?.check()
        }
        timer?.tolerance = 0.2
    }

    func stop() {
        precondition(Thread.isMainThread)
        timer?.invalidate()
        timer = nil
        if let activationObserver {
            NSWorkspace.shared.notificationCenter.removeObserver(activationObserver)
            self.activationObserver = nil
        }
    }

    func refreshAuthorization() {
        precondition(Thread.isMainThread)
        if ClipboardAccess.current == .denied {
            notifySkipped(.pasteboardAccessDenied)
        }
    }

    private func applicationDidActivate(_ notification: Notification) {
        precondition(Thread.isMainThread)
        let application = notification.userInfo?[NSWorkspace.applicationUserInfoKey] as? NSRunningApplication
        let newBundleID = application?.bundleIdentifier

        if let previous = lastActivatedBundleID,
           Settings.excludedApps.contains(previous),
           previous != newBundleID {
            excludedChangeGuard.record(changeCount: NSPasteboard.general.changeCount)
            excludedTransitionUntil = Date().addingTimeInterval(ClipboardCapturePolicy.excludedActivationWindow)
        }
        lastActivatedBundleID = newBundleID
    }

    /// The timer only observes policy state and snapshots immutable pasteboard
    /// values. Decode, hashing and every DB call run serially
    /// on `processingQueue`.
    private func check() {
        precondition(Thread.isMainThread)
        let pasteboard = NSPasteboard.general
        let changeCount = pasteboard.changeCount
        // Also lets a persisted timed pause expire and notify the UI even when
        // the clipboard has remained unchanged.
        let capturePaused = Settings.isCapturePaused
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount

        if ClipboardWriteGuard.shared.consumeIfOwn(changeCount: changeCount) {
            notifySkipped(.ownWrite)
            return
        }
        if Settings.consumeIgnoreNextCopy() {
            notifySkipped(.ignoredOnce)
            return
        }
        if capturePaused {
            notifySkipped(.paused)
            return
        }

        guard ClipboardAccess.current.permitsBackgroundRead else {
            notifySkipped(.pasteboardAccessDenied)
            return
        }

        let types = Set(pasteboard.types ?? [])
        guard types.isDisjoint(with: Self.concealedTypes) else {
            notifySkipped(.protectedType)
            return
        }

        let now = Date()
        let frontApp = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        let transitionActive = excludedTransitionUntil.map { $0 > now } ?? false
        let exactExcludedChange = excludedChangeGuard.consumeIfExcluded(changeCount: changeCount)
        if !transitionActive { excludedTransitionUntil = nil }
        guard !ClipboardCapturePolicy.shouldRejectSource(
            bundleID: frontApp,
            excludedTransitionActive: transitionActive || exactExcludedChange,
            excludedApps: Set(Settings.excludedApps)
        ), let frontApp else {
            notifySkipped(.excludedOrUnknownSource)
            return
        }

        // Respect the representation priority while snapshotting as well, so
        // a file/image copy does not also pull a large RTF/text payload through
        // the main thread.
        let fileURLs = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL] ?? []
        if fileURLs.isEmpty,
           !Settings.captureImages,
           types.contains(.png) || types.contains(.tiff) {
            notifySkipped(.disabledContentType)
            return
        }
        let pngData = fileURLs.isEmpty ? pasteboard.data(forType: .png) : nil
        let imageData = pngData ?? (fileURLs.isEmpty ? pasteboard.data(forType: .tiff) : nil)
        let text = fileURLs.isEmpty && imageData == nil
            ? pasteboard.string(forType: .string)
            : nil
        let rtf = text == nil ? nil : pasteboard.data(forType: .rtf)
        // A different process may replace the pasteboard while representations
        // are being read. Discard a mixed snapshot; the next timer tick will
        // observe and process the newer generation with fresh attribution.
        guard pasteboard.changeCount == changeCount else { return }
        let snapshot = Snapshot(
            changeCount: changeCount,
            appBundleID: frontApp,
            createdAt: now,
            fileURLs: fileURLs,
            imageData: imageData,
            imageDataIsPNG: pngData != nil,
            text: text,
            rtf: rtf
        )

        processingQueue.async { [weak self] in
            autoreleasepool {
                self?.process(snapshot)
            }
        }
    }

    private func process(_ snapshot: Snapshot) {
        if !snapshot.fileURLs.isEmpty {
            processFiles(snapshot)
        } else if let imageData = snapshot.imageData {
            processImage(imageData, isPNG: snapshot.imageDataIsPNG, snapshot: snapshot)
        } else if let text = snapshot.text {
            processText(text, snapshot: snapshot)
        } else {
            notifySkipped(.empty)
        }
    }

    private func processFiles(_ snapshot: Snapshot) {
        guard snapshot.fileURLs.count <= ClipboardCapturePolicy.maxFileCount else {
            notifySkipped(.tooLarge)
            return
        }
        let title = snapshot.fileURLs.map(\.lastPathComponent).joined(separator: ", ")
        let paths = snapshot.fileURLs.map(\.path).joined(separator: "\n")
        let pathData = Data(paths.utf8)
        guard pathData.count <= ClipboardCapturePolicy.maxTextBytes else {
            notifySkipped(.tooLarge)
            return
        }

        let item = ClipItem(
            kind: .file,
            title: title,
            text: paths,
            appBundleID: snapshot.appBundleID,
            createdAt: snapshot.createdAt,
            contentBytes: Int64(pathData.count),
            contentHash: Self.sha256(pathData)
        )
        insert(item)
    }

    private func processText(_ text: String, snapshot: Snapshot) {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else {
            notifySkipped(.empty)
            return
        }
        guard !SensitiveContentPolicy.matches(
            text,
            normalizedRules: Settings.sensitiveContentRules
        ) else {
            notifySkipped(.sensitiveContent)
            return
        }

        let textData = Data(text.utf8)
        let payloadLimit = ClipboardCapturePolicy.effectiveTextPayloadLimit(
            userLimit: Settings.maximumTextCaptureBytes
        )
        guard ClipboardCapturePolicy.acceptsTextPayload(
            textBytes: textData.count,
            rtfBytes: 0,
            userLimit: payloadLimit
        ) else {
            notifySkipped(.tooLarge)
            return
        }
        let safeRTF = snapshot.rtf.flatMap {
            $0.count <= ClipboardCapturePolicy.maxRTFBytes
                && ClipboardCapturePolicy.acceptsTextPayload(
                    textBytes: textData.count,
                    rtfBytes: $0.count,
                    userLimit: payloadLimit
                ) ? $0 : nil
        }
        let title = String(trimmed.prefix(200)).replacingOccurrences(of: "\n", with: " ")
        let item = ClipItem(
            kind: .text,
            title: title,
            text: text,
            rtf: safeRTF,
            appBundleID: snapshot.appBundleID,
            createdAt: snapshot.createdAt,
            contentBytes: Int64(textData.count + (safeRTF?.count ?? 0)),
            contentHash: Self.sha256(textData)
        )
        insert(item)
    }

    private func processImage(_ imageData: Data, isPNG: Bool, snapshot: Snapshot) {
        guard Settings.captureImages else {
            notifySkipped(.disabledContentType)
            return
        }
        guard imageData.count <= ClipboardCapturePolicy.maxEncodedImageBytes,
              let source = CGImageSourceCreateWithData(imageData as CFData, nil),
              let dimensions = Self.dimensions(of: source) else {
            notifySkipped(imageData.count > ClipboardCapturePolicy.maxEncodedImageBytes ? .tooLarge : .invalidImage)
            return
        }
        guard ClipboardCapturePolicy.acceptsImage(
            byteCount: imageData.count,
            width: dimensions.width,
            height: dimensions.height
        ) else {
            notifySkipped(.tooLarge)
            return
        }
        let png: Data
        if isPNG {
            png = imageData
        } else if let converted = Self.pngData(from: source) {
            png = converted
        } else {
            notifySkipped(.invalidImage)
            return
        }
        guard png.count <= ClipboardCapturePolicy.maxEncodedImageBytes else {
            notifySkipped(.tooLarge)
            return
        }

        let item = ClipItem(
            kind: .image,
            title: "Image \(dimensions.width)×\(dimensions.height)",
            data: png,
            appBundleID: snapshot.appBundleID,
            createdAt: snapshot.createdAt,
            contentBytes: Int64(png.count),
            contentHash: Self.sha256(png)
        )

        do {
            let clipID = try Storage.shared.insert(item)
            if let clipID {
                SequentialPasteSequence.shared.noteExternalCapture()
                OCRService.recognize(imageData: png, clipID: clipID)
            }
        } catch {
            captureFailed(error)
        }
    }

    private func insert(_ item: ClipItem) {
        do {
            if try Storage.shared.insert(item) != nil {
                SequentialPasteSequence.shared.noteExternalCapture()
            }
        } catch {
            captureFailed(error)
        }
    }

    private func captureFailed(_ error: Error) {
        DispatchQueue.main.async { [weak self] in
            NotificationCenter.default.post(
                name: .neClipCaptureDidFail,
                object: self,
                userInfo: ["error": error]
            )
        }
    }

    private func notifySkipped(_ reason: ClipboardCaptureSkipReason) {
        DispatchQueue.main.async { [weak self] in
            NotificationCenter.default.post(
                name: .neClipCaptureDidSkip,
                object: self,
                userInfo: ["reason": reason.rawValue, "skipReason": reason]
            )
        }
    }

    private static func dimensions(of source: CGImageSource) -> (width: Int, height: Int)? {
        guard let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
              let width = (properties[kCGImagePropertyPixelWidth] as? NSNumber)?.intValue,
              let height = (properties[kCGImagePropertyPixelHeight] as? NSNumber)?.intValue else {
            return nil
        }
        return (width, height)
    }

    private static func pngData(from source: CGImageSource) -> Data? {
        guard let image = CGImageSourceCreateImageAtIndex(source, 0, nil) else { return nil }
        return encodedPNG(image)
    }

    private static func encodedPNG(_ image: CGImage) -> Data? {
        let data = NSMutableData()
        guard let destination = CGImageDestinationCreateWithData(
            data,
            UTType.png.identifier as CFString,
            1,
            nil
        ) else { return nil }
        CGImageDestinationAddImage(destination, image, nil)
        guard CGImageDestinationFinalize(destination) else { return nil }
        return data as Data
    }

    private static func sha256(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }
}
